---

- name: Include specific Elasticsearch
  import_tasks: elasticsearch-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific Elasticsearch
  import_tasks: elasticsearch-RedHat.yml
  when: ansible_os_family == 'RedHat'
